<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.oracle.coherence</groupId>
        <artifactId>coherence-native-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>coherence-native-testing-support</artifactId>
    <name>Coherence GraalVM Native Testing Support</name>
    <description>Oracle Coherence GraalVM native image testing support utils</description>
    <packaging>jar</packaging>
    <properties>
      <coherence.groupId>com.oracle.coherence.ce</coherence.groupId>
      <version.lib.coherence>25.03.1</version.lib.coherence>
    </properties>
    <dependencies>
        <dependency>
            <groupId>${coherence.groupId}</groupId>
            <artifactId>coherence</artifactId>
        </dependency>

        <dependency>
            <groupId>${coherence.groupId}</groupId>
            <artifactId>coherence-bedrock-testing-support</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>${coherence.groupId}</groupId>
                <artifactId>pof-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>instrument</id>
                        <goals>
                            <goal>instrument</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
